name: source-update
on:
  workflow_dispatch:
  push:
    branches-ignore: ['main', 'integration']
    paths:
      - 'src/**'
      - 'pom.xml'
jobs:
  buildtest:
    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        java: [ '8' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn --batch-mode test


  
